/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import java.awt.Color;
import login.AdminLogin;

/**
 *
 * @author Dell
 */
public class AdminForm extends javax.swing.JFrame {
   //Maha's code
    //nextline wich includes File identification 
      FileWriter file;
       //to convert id data type
 
  String idtostring;
     //end of Maha's code
    
    public AdminForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EmpDesignation = new javax.swing.JLabel();
        btn5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jp1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jemp = new javax.swing.JButton();
        jp3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlogout = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addempanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jaddemp = new javax.swing.JButton();
        viewempanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jviewemp = new javax.swing.JButton();
        deletempanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jdeletemp = new javax.swing.JButton();
        p4 = new javax.swing.JPanel();
        txtfname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        combogen = new javax.swing.JComboBox<>();
        jupdate = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jreset = new javax.swing.JButton();
        p5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jbenter = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        p6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        p7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        jPanel1.setMinimumSize(new java.awt.Dimension(1500, 780));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new Color(213, 134, 145, 123));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(0, 0, 104));
        SidePanel.setPreferredSize(new java.awt.Dimension(130, 600));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_user_male_100px.png"))); // NOI18N
        SidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 70));

        EmpDesignation.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        EmpDesignation.setForeground(new java.awt.Color(102, 204, 255));
        EmpDesignation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmpDesignation.setText("Owner");
        SidePanel.add(EmpDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, 20));

        btn5.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Options");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout btn5Layout = new javax.swing.GroupLayout(btn5);
        btn5.setLayout(btn5Layout);
        btn5Layout.setHorizontalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btn5Layout.setVerticalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        SidePanel.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        jp1.setBackground(new java.awt.Color(0, 0, 51));
        jp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_collaboration_female_male_40px.png"))); // NOI18N
        jp1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 130, 30));

        jemp.setBackground(new java.awt.Color(0, 0, 0));
        jemp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jemp.setForeground(new java.awt.Color(255, 255, 255));
        jemp.setText("Employees");
        jemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jempActionPerformed(evt);
            }
        });
        jp1.add(jemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 40, 100, 20));

        SidePanel.add(jp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 160, 124, 60));

        jp3.setBackground(new java.awt.Color(0, 0, 51));
        jp3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Logout_40px.png"))); // NOI18N
        jp3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 130, 30));

        jlogout.setBackground(new java.awt.Color(0, 0, 0));
        jlogout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlogout.setForeground(new java.awt.Color(255, 255, 255));
        jlogout.setText("Log Out");
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        jp3.add(jlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 40, 100, 20));

        SidePanel.add(jp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 124, 60));

        mainPanel.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 660));

        centerPanel.setLayout(new java.awt.CardLayout());

        p1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel11.setBackground(new Color(213, 134, 145, 123));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/b718b792b6266d4b8ab25dfc630908d3.jpg"))); // NOI18N

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addContainerGap())
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        centerPanel.add(p1, "card3");

        p2.setBackground(new java.awt.Color(218, 228, 230));
        p2.setForeground(new java.awt.Color(240, 240, 240));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 204, 255));
        jLabel7.setText("Welcome To Employee Management System");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Employee Section");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_info_20px.png"))); // NOI18N

        addempanel.setBackground(new java.awt.Color(255, 255, 255));
        addempanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        addempanel.setPreferredSize(new java.awt.Dimension(170, 120));
        addempanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_user_male_skin_type_7_96px.png"))); // NOI18N
        addempanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 131, 100));

        jaddemp.setBackground(new java.awt.Color(255, 255, 255));
        jaddemp.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jaddemp.setForeground(new java.awt.Color(0, 153, 0));
        jaddemp.setText("Add Employee");
        jaddemp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jaddemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddempActionPerformed(evt);
            }
        });
        addempanel.add(jaddemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        viewempanel.setBackground(new java.awt.Color(255, 255, 255));
        viewempanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        viewempanel.setPreferredSize(new java.awt.Dimension(170, 120));
        viewempanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_apply_96px.png"))); // NOI18N
        viewempanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 131, 100));

        jviewemp.setBackground(new java.awt.Color(255, 255, 255));
        jviewemp.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jviewemp.setForeground(new java.awt.Color(0, 0, 255));
        jviewemp.setText("View Employee");
        jviewemp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jviewemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jviewempActionPerformed(evt);
            }
        });
        viewempanel.add(jviewemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        deletempanel.setBackground(new java.awt.Color(255, 255, 255));
        deletempanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(153, 153, 153)));
        deletempanel.setPreferredSize(new java.awt.Dimension(170, 120));
        deletempanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_denied_skin_type_7_96px.png"))); // NOI18N
        deletempanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 131, 90));

        jdeletemp.setBackground(new java.awt.Color(255, 255, 255));
        jdeletemp.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jdeletemp.setForeground(new java.awt.Color(204, 0, 51));
        jdeletemp.setText("Delete Employee");
        jdeletemp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jdeletemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeletempActionPerformed(evt);
            }
        });
        deletempanel.add(jdeletemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, -1));

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(addempanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(deletempanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewempanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(addempanel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewempanel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(deletempanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        centerPanel.add(p2, "card2");

        p4.setBackground(new java.awt.Color(218, 228, 230));
        p4.setForeground(new java.awt.Color(255, 255, 255));

        txtfname.setBackground(new java.awt.Color(0, 0, 0));
        txtfname.setForeground(new java.awt.Color(255, 255, 255));
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("First Name");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Last Name");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Age");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Gender");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Phone Number");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Salary");

        txtlname.setBackground(new java.awt.Color(0, 0, 0));
        txtlname.setForeground(new java.awt.Color(255, 255, 255));

        txtage.setBackground(new java.awt.Color(0, 0, 0));
        txtage.setForeground(new java.awt.Color(255, 255, 255));

        txtnum.setBackground(new java.awt.Color(0, 0, 0));
        txtnum.setForeground(new java.awt.Color(255, 255, 255));

        txtsalary.setBackground(new java.awt.Color(0, 0, 0));
        txtsalary.setForeground(new java.awt.Color(255, 255, 255));

        combogen.setBackground(new java.awt.Color(0, 0, 0));
        combogen.setForeground(new java.awt.Color(255, 255, 255));
        combogen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        combogen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogenActionPerformed(evt);
            }
        });

        jupdate.setBackground(new java.awt.Color(255, 255, 255));
        jupdate.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jupdate.setText("Update");
        jupdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Address");

        txtaddress.setBackground(new java.awt.Color(0, 0, 0));
        txtaddress.setForeground(new java.awt.Color(255, 255, 255));
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        jreset.setBackground(new java.awt.Color(255, 255, 255));
        jreset.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jreset.setText("Reset");
        jreset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p4Layout.createSequentialGroup()
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsalary)
                    .addComponent(txtfname)
                    .addComponent(txtlname)
                    .addComponent(txtage)
                    .addComponent(combogen, 0, 81, Short.MAX_VALUE)
                    .addComponent(txtnum)
                    .addComponent(txtaddress))
                .addGap(126, 126, 126)
                .addComponent(jreset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addGap(42, 42, 42)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(39, 39, 39)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(combogen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jupdate)
                            .addComponent(jreset))
                        .addGap(46, 46, 46)))
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        centerPanel.add(p4, "card5");

        p5.setBackground(new java.awt.Color(218, 228, 230));
        p5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Employee's ID");

        jbenter.setBackground(new java.awt.Color(255, 255, 255));
        jbenter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbenter.setText("Enter");
        jbenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbenterActionPerformed(evt);
            }
        });

        txtid.setBackground(new java.awt.Color(0, 0, 0));
        txtid.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p5Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel22)
                        .addGap(63, 63, 63)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p5Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jbenter, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jbenter)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        centerPanel.add(p5, "card6");

        p6.setBackground(new java.awt.Color(218, 228, 230));
        p6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("Employee's ID");

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("Enter");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p6Layout = new javax.swing.GroupLayout(p6);
        p6.setLayout(p6Layout);
        p6Layout.setHorizontalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p6Layout.createSequentialGroup()
                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p6Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel23)
                        .addGap(59, 59, 59)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p6Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        p6Layout.setVerticalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p6Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(jButton1)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        centerPanel.add(p6, "card7");

        p7.setBackground(new java.awt.Color(218, 228, 230));
        p7.setForeground(new java.awt.Color(255, 255, 255));
        p7.setPreferredSize(new java.awt.Dimension(789, 560));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout p7Layout = new javax.swing.GroupLayout(p7);
        p7.setLayout(p7Layout);
        p7Layout.setHorizontalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p7Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        p7Layout.setVerticalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p7Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        centerPanel.add(p7, "card8");

        mainPanel.add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 15, 760, 580));

        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 920, 600));

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 690, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 80)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Admin Management");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 720, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/3014741.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jempActionPerformed
        // TODO add your handling code here:
        p2.setVisible(true);
        p1.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
    }//GEN-LAST:event_jempActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"LogOut successfully","",JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jaddempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddempActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p4.setVisible(true);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
    }//GEN-LAST:event_jaddempActionPerformed

    private void jviewempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jviewempActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(true);
        p7.setVisible(false);
    }//GEN-LAST:event_jviewempActionPerformed

    private void jdeletempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeletempActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(true);
        p6.setVisible(false);
        p7.setVisible(false);
        //abcde
    }//GEN-LAST:event_jdeletempActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void combogenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combogenActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
        // TODO add your handling code here:
        String str = txtfname.getText()+ txtlname.getText();
        int id=0;
        for(int i=0; i<str.length();i++) {
            id+=str.charAt(i);

        }

        //Maha's code

        idtostring= Integer.toString(id);
        // the following code adds data of emploee to file named EmploeesData
        if( evt.getSource()==jupdate)
        {
            try{//To creat file
                file= new FileWriter("EmploeeData.txt",true);
                //to add Id After convesion
                file.write(idtostring+"  ");

                //to add First name
                file.write(jLabel14.getText()+" : "+txtfname.getText()+"");
                // to add Last name
                file.write(jLabel16.getText()+" : "+txtlname.getText()+"");
                //to add age
                file.write(jLabel17.getText()+" : "+txtage.getText());
                //to add Gender
                file.write(jLabel18.getText()+" : "+combogen.getSelectedItem()+"");
                //to add phone number
                file.write(jLabel19.getText()+" : "+txtnum.getText()+"");
                //to add salary
                file.write(jLabel20.getText()+" : "+txtsalary.getText()+"");
                //to add address
                file.write(jLabel21.getText()+" : "+txtaddress.getText()+"");
                // to indicate end of emploees' data
                // file.write("# \n");
                file.close();
            }   catch(Exception e ){
                JOptionPane.showMessageDialog(null, "Error");}
        }

        //End of Maha's code

        Scanner scanner = new Scanner(System.in);
        File file= new File("src\\wav\\Bell.wav");
        try {
            AudioInputStream as= AudioSystem.getAudioInputStream(file);
            Clip clip= AudioSystem.getClip();
            clip.open(as);
            clip.start();

        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this,"the employee's info has been successfully uploaded","",JOptionPane.INFORMATION_MESSAGE);
        // Scanner scanner = new Scanner(System.in);
        //File file= new File("src\\wav\\Bell.wav");
        try {
            AudioInputStream as= AudioSystem.getAudioInputStream(file);
            Clip clip= AudioSystem.getClip();
            clip.open(as);
            clip.start();

        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this,"the employee's ID: "+id,"",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jupdateActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        // TODO add your handling code here:
        txtfname.setText(null);
        txtlname.setText(null);
        txtage.setText(null);
        txtnum.setText(null);
        txtsalary.setText(null);
        txtaddress.setText(null);
    }//GEN-LAST:event_jresetActionPerformed

    private void jbenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbenterActionPerformed
        // TODO add your handling code here:
        //Maha's code
        String Line ;
        try{ txtid.getText();
            //TO access the data of emploee
            Scanner x= new Scanner(new File("EmploeeData.txt"));
            //To get updated file
            FileWriter newf= new FileWriter(" UpdatedEMploeeInfo.txt",true);
            //To search in FIle and delete
            while(x.hasNext())
            {idtostring=txtid.getText();
                Line = x.nextLine();
                //System.out.println(idtostring);
                //System.out.println(txtid.getText());
                //if ( idtostring.equals(txtid.getText())){
                    //newf.write(Line);
                    //}
                //else{
                    //newf.write(Line);
                    //}
                // newf.write(Line);
                //  jTextArea1.setText(Line);
                if(Line.startsWith(idtostring)){

                    newf.write(x.nextLine());

                }

            }
            x.close();
            newf.close();
        }
        catch(IOException ex){
            System.out.println("CAn't be reached");}
        //end of Maha's code
        Scanner scanner = new Scanner(System.in);
        File file= new File("src\\wav\\Bell.wav");
        try {
            AudioInputStream as= AudioSystem.getAudioInputStream(file);
            Clip clip= AudioSystem.getClip();
            clip.open(as);
            clip.start();

        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this,"the employee's info has been deleted successfully","",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbenterActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(true);
        //Maha's code
        String Line ;
        try{
            //TO access the data of emploee
            Scanner x= new Scanner(new File("EmploeeData.txt"));
            //To get updated file
            // FileWriter newf= new FileWriter(" UpdatedEMploeeInfo.txt",true);
            //To search in FIle and delete
            while(x.hasNext()){
                Line = x.nextLine();
                // newf.write(Line);
                // jTextArea1.setText(Line);

                idtostring=jTextField1.getText();
                if( Line.startsWith(idtostring )){

                    jTextArea1.setText(Line);
                    // newf.write(temp);

                }
                //&& Line.endsWith("#")

            }
            x.close();
            // newf.close();
        }
        catch(IOException ex){
            System.out.println("CAn't be reached");}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminLogin obj = new AdminLogin();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmpDesignation;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel addempanel;
    private javax.swing.JPanel btn5;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JComboBox<String> combogen;
    private javax.swing.JPanel deletempanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jaddemp;
    private javax.swing.JButton jbenter;
    private javax.swing.JButton jdeletemp;
    private javax.swing.JButton jemp;
    private javax.swing.JButton jlogout;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp3;
    private javax.swing.JButton jreset;
    private javax.swing.JButton jupdate;
    private javax.swing.JButton jviewemp;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p7;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JPanel viewempanel;
    // End of variables declaration//GEN-END:variables
}
